name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Execute remote ssh commands
      run: echo 'pas 1'
      #uses: appleboy/ssh-action@master


