name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Execute remote ssh commands
      run:
        echo ${{ secrets.SSH_PRIVATE_KEY }}
        
      


